# Generated by Django 4.2.4 on 2025-03-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180403_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='upd_date',
        ),
    ]
