# Generated by Django 4.2.4 on 2025-03-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_userprofile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='found_date',
        ),
    ]
